name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files to be deployed (debug)
        run: |
          echo "== Listing repository root =="
          ls -la
          echo "\n== Check for index.html and assets folder =="
          if [ -f index.html ]; then echo "index.html: FOUND"; else echo "index.html: MISSING"; fi
          if [ -d assets ]; then echo "assets/: FOUND"; else echo "assets/: MISSING"; fi
          echo "\n== Disk usage (top-level) =="
          du -sh ./* || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
